// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSIONS_KV: KVNamespace;
	EMAIL_ADDRESS_TOKEN: "MS._d7Jq3wX8vL-qYp2LcZBsTt.oA4GiL-xekW9PdQnHXIZnQy582KJdrV1yuEVkzOCwq";
	SCOPES: "write_products";
	SHOPIFY_APP_HANDLE: string;
	SHOPIFY_APP_ID: string;
	DB_SUBSCRIPTIONS: D1Database;
}
